name: Deploy git tag  

# Only run after a pull request has been merged. This is because
# bot account runs write operations on the github repo to push a tag. 
on:
  push:
    branches: [main, beta, alpha]

jobs:
  deploy-sdk:
    name: Deploy git tag
    runs-on: ubuntu-latest
    steps:    
      - name: semantic-release setup
        uses: levibostian/action-semantic-release-justwork@v1
        
      - name: Setup Ruby to run Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically        
      
      - name: Deploy git tag via semantic-release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 18
          extra_plugins: |
            conventional-changelog-conventionalcommits@4
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/github@8
            @semantic-release/exec@6
        env:
          GITHUB_TOKEN: ${{ secrets.WRITE_ACCESS_BOT_TOKEN }}
          
        